version: "3.7"

services:
  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: test
      TZ: "Asia/Tokyo"
    restart: always
volumes:
  db-data: